version: "3"

services:
  app:
    container_name: yelp
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
